export const missionCatalog = [
  {id:'daily-signal',title:'Your daily gift',description:'Check in today and collect your daily reward.',icon:'capsule',category:'daily',route:'rewards',progress:1,target:1,amount:'0.02',state:'verified',steps:[['Open mission control','Visit your Tasks tab today.'],['Collect today’s energy','One check-in is counted per calendar day.'],['Claim your TON','Collect your confirmed daily reward.']]},
  {id:'daily-explorer',title:'The discovery trail',description:'Discover three corners of the CASE universe.',icon:'compass',category:'daily',route:'home',progress:1,target:3,amount:'0.03',steps:[['Visit collections','Explore the collection catalogue.'],['Discover achievements','Find a milestone you want to reach.'],['Meet the community','Open the official CASE community page.']]},
  {id:'daily-code',title:'Find the hidden gift',description:'Find today’s clue in the community update.',icon:'satellite',category:'daily',route:'channel',progress:0,target:1,amount:'0.02',steps:[['Read the latest update','Open today’s official community update.'],['Find the clue','Look for the mission clue in the post.'],['Submit your answer','Enter the answer in the host mission flow.']]},
  {id:'daily-quiz',title:'Know your collection',description:'Three questions. A sharper collector’s eye.',icon:'gem',category:'daily',route:'collection',progress:1,target:3,amount:'0.04',steps:[['Explore the collection','Look at the featured items and their details.'],['Take the mini quiz','Answer three collection questions in CASE.'],['Reveal your result','Your reward unlocks after the correct answers are confirmed.']]},
  {id:'daily-save',title:'Your first shortlist',description:'Save three collectibles you would love to own.',icon:'ticket',category:'daily',route:'collection',progress:0,target:3,amount:'0.02',steps:[['Find your favourites','Browse the collectible catalogue.'],['Build a shortlist','Save three different items using the host favourites control.'],['Finish your selection','Return to Tasks to check your progress.']]},
  {id:'daily-profile',title:'Make it yours',description:'Choose your display name and profile style.',icon:'check',category:'daily',route:'profile',progress:0,target:2,amount:'0.02',steps:[['Choose your name','Set your public display name.'],['Pick a profile style','Choose an avatar or style from the available options.'],['Save your profile','Confirm your changes in CASE.']]},
  {id:'limited-passport',title:'The collector’s set',description:'Complete four challenges inspired by iconic collectibles.',icon:'ticket',category:'limited',route:'collection',progress:2,target:4,amount:'0.12',featured:true,steps:[['Discover two collections','Browse two featured collections to get your first stamps.'],['Find the hidden detail','Complete the featured collection question.'],['Complete your set','Finish the community mission for the final stamp.']]},
  {id:'limited-streak',title:'A week of gifts',description:'Come back for seven days. Unlock your weekly reward.',icon:'capsule',category:'limited',route:'weekly',progress:3,target:7,amount:'0.10',steps:[['Collect a daily stamp','Complete the daily check-in.'],['Keep the sequence','Return on seven consecutive days.'],['Unlock your weekly gift','The final cell unlocks your weekly reward.']]},
  {id:'limited-crew',title:'Better with friends',description:'You and a friend. Two explorers, one shared goal.',icon:'users',category:'limited',route:'invite',progress:0,target:2,amount:'0.08',steps:[['Invite your crew mate','Share your invitation with a new friend.'],['Explore together','Both complete the discovery trail.'],['Finish the expedition','Receive the reward after both milestones are confirmed.']]},
  {id:'limited-curator',title:'Community curator',description:'Vote for the theme of the next collection.',icon:'crown',category:'limited',route:'channel',progress:0,target:1,amount:'0.03',steps:[['Meet the candidates','Explore the proposed collection themes.'],['Cast your vote','Choose one theme in the official poll.'],['Collect your badge','Return when your participation is verified.']]},
  {id:'social-channel',title:'Join the inner circle',description:'Follow CASE for drops, news and mission clues.',icon:'send',category:'social',route:'channel',progress:0,target:1,amount:'0.03',steps:[['Open the CASE channel','Visit the official channel linked by CASE.'],['Join the community','Subscribe to the channel.'],['Verify your membership','Return here and check your subscription.']]},
  {id:'social-partner',title:'Partner gift drop',description:'Discover a partner community and join the channel.',icon:'satellite',category:'social',route:'channel',progress:0,target:1,amount:'0.04',steps:[['Discover the partner','Open the campaign’s partner channel.'],['Join their channel','Subscribe and explore the community.'],['Return to claim','Check your membership inside CASE.']]},
  {id:'social-invite',title:'Bring your plus one',description:'Invite a friend to complete their first mission.',icon:'users',category:'social',route:'invite',progress:0,target:1,amount:'0.05',steps:[['Send your invitation','Share your personal invite link.'],['Welcome your friend','Your friend joins CASE through that invitation.'],['Complete the first mission','The reward unlocks when the qualifying mission is confirmed.']]},
  {id:'social-feedback',title:'Help shape CASE',description:'Share your feedback in a short community survey.',icon:'check',category:'social',route:'channel',progress:0,target:1,amount:'0.02',steps:[['Open the survey','Find the active feedback form.'],['Share your experience','Answer the short set of product questions.'],['Submit your feedback','Return after your submission is recorded.']]},
  {id:'social-read',title:'Behind the drop',description:'Discover the story behind a featured collectible.',icon:'gem',category:'social',route:'collection',progress:0,target:1,amount:'0.02',steps:[['Read the story','Open the featured collectible’s story.'],['Find the detail','Answer one question about the collectible.'],['Complete the mission','Your answer is checked by CASE.']]},
  {id:'social-vote',title:'Pick the next mission',description:'Help choose the next community challenge.',icon:'trophy',category:'social',route:'channel',progress:0,target:1,amount:'0.02',steps:[['See the proposals','Explore this week’s mission ideas.'],['Choose your favourite','Vote in the community poll.'],['Make your voice count','Your participation is confirmed before the reward unlocks.']]}
];
