export const missionCatalog = [
  {id:'daily-signal',title:'Daily check-in',description:'Open CASE and activate today’s route.',icon:'check',category:'daily',route:'rewards',progress:1,target:1,amount:'0.01',state:'verified',steps:[['Open Tasks','Visit the Tasks tab today.'],['Activate the route','Start the current mission route.'],['Claim your TON','Collect the confirmed daily reward.']]},
  {id:'daily-explorer',title:'Visit partner',description:'Open the featured partner page and explore the offer.',icon:'rocket',category:'daily',route:'home',progress:1,target:2,amount:'0.03',steps:[['Open the partner page','Follow the campaign link provided by CASE.'],['Explore the offer','Spend enough time to understand the featured product.'],['Return to CASE','Come back to confirm the visit.']]},
  {id:'daily-code',title:'Find campaign code',description:'Read the latest partner post and find the hidden code.',icon:'send',category:'daily',route:'channel',progress:0,target:1,amount:'0.02',steps:[['Open the featured post','Visit the current partner publication.'],['Find the code','Look for the highlighted word or campaign code.'],['Submit the answer','Enter it in the campaign flow.']]},
  {id:'daily-quiz',title:'Quick partner quiz',description:'Answer three short questions about today’s campaign.',icon:'star',category:'daily',route:'collection',progress:1,target:3,amount:'0.04',steps:[['Explore the campaign','Review the featured partner page.'],['Take the quiz','Answer three short questions.'],['Confirm the result','The reward unlocks after verification.']]},
  {id:'daily-save',title:'Save the featured offer',description:'Add today’s partner offer to your saved list.',icon:'grid',category:'daily',route:'collection',progress:0,target:1,amount:'0.02',steps:[['Open the offer','Visit the featured campaign page.'],['Save it','Use the partner or CASE save control.'],['Check progress','Return to Tasks to verify the action.']]},
  {id:'daily-profile',title:'Campaign profile',description:'Add the details needed for campaign participation.',icon:'gem',category:'daily',route:'profile',progress:0,target:2,amount:'0.02',steps:[['Open your profile','Go to the CASE profile section.'],['Add the required details','Complete the fields needed for partner missions.'],['Save changes','Confirm your profile update.']]},
  {id:'limited-passport',title:'Partner passport',description:'Visit four featured partners and collect every stamp.',icon:'ticket',category:'limited',route:'collection',progress:2,target:4,amount:'0.12',featured:true,steps:[['Discover the partners','Open four featured campaign pages.'],['Complete each action','Follow the requirement shown on every page.'],['Finish the passport','Return after all four visits are verified.']]},
  {id:'limited-streak',title:'Seven-day route',description:'Complete one partner mission every day for a week.',icon:'sun',category:'limited',route:'weekly',progress:3,target:7,amount:'0.10',steps:[['Choose a daily mission','Open any active partner campaign.'],['Keep the sequence','Complete one mission on seven consecutive days.'],['Unlock the weekly bonus','Claim after the final day is confirmed.']]},
  {id:'limited-crew',title:'Explore with a friend',description:'Invite a friend and complete a partner route together.',icon:'users',category:'limited',route:'invite',progress:0,target:2,amount:'0.08',steps:[['Invite a friend','Share your personal CASE link.'],['Choose a campaign','Open the same featured partner route.'],['Finish together','The reward unlocks after both actions are confirmed.']]},
  {id:'limited-curator',title:'Choose the next sponsor',description:'Vote for the campaign you want to see next.',icon:'crown',category:'limited',route:'channel',progress:0,target:1,amount:'0.03',steps:[['Meet the candidates','Explore the proposed partner campaigns.'],['Cast your vote','Choose one in the official poll.'],['Return to CASE','Confirm your participation.']]},
  {id:'social-channel',title:'Join the partner channel',description:'Subscribe to today’s featured partner community.',icon:'send',category:'social',route:'channel',progress:0,target:1,amount:'0.03',steps:[['Open the channel','Follow the verified campaign link.'],['Join the community','Subscribe to the partner channel.'],['Verify membership','Return to CASE and check the action.']]},
  {id:'social-partner',title:'Try the partner bot',description:'Open the featured bot and complete its welcome action.',icon:'rocket',category:'social',route:'channel',progress:0,target:1,amount:'0.04',steps:[['Open the bot','Use the verified link inside CASE.'],['Complete the welcome action','Follow the short partner flow.'],['Return to claim','Check completion inside CASE.']]},
  {id:'social-invite',title:'Bring a friend',description:'Invite one new user who completes the partner action.',icon:'users',category:'social',route:'invite',progress:0,target:1,amount:'0.05',steps:[['Share your invite','Send your personal campaign link.'],['Welcome your friend','They join through that link.'],['Complete the action','The reward unlocks after their qualifying action.']]},
  {id:'social-feedback',title:'Rate the campaign',description:'Share a quick reaction after visiting the partner.',icon:'check',category:'social',route:'channel',progress:0,target:1,amount:'0.02',steps:[['Visit the campaign','Explore the featured partner page.'],['Open the survey','Answer the short feedback form.'],['Submit your rating','Return after the response is recorded.']]},
  {id:'social-read',title:'Read the sponsor story',description:'Discover the partner’s story and answer one question.',icon:'star',category:'social',route:'collection',progress:0,target:1,amount:'0.02',steps:[['Open the story','Visit the featured partner article.'],['Find the key detail','Read the short campaign story.'],['Answer the question','Submit the correct detail inside CASE.']]},
  {id:'social-vote',title:'Pick tomorrow’s route',description:'Choose which partner mission appears next.',icon:'trophy',category:'social',route:'channel',progress:0,target:1,amount:'0.02',steps:[['View the options','Explore tomorrow’s proposed campaigns.'],['Choose one','Vote in the official poll.'],['Confirm the vote','Return after participation is recorded.']]}
];
